version: '3.3'

services:
  app:
    image: docker.sendgrid.net/sendgrid/ui-components:latest
    build:
     context: .  
    volumes:
      - ./dist:/opt/sendgrid/ui-components/dist
      - ./storybookDist:/opt/sendgrid/ui-components/storybookDist
  develop:
    image: docker.sendgrid.net/sendgrid/ui-components:latest
    build:
      context: .
    volumes:
    - /opt/sendgrid/ui-components/node_modules
    - .:/opt/sendgrid/ui-components
    ports:
    - "6006:6006"
