version: '3.3'

services:
  app:
    image: docker.sendgrid.net/sendgrid/ui-components:latest
    user: ${MYUID:-0}
    build:
     context: .  
    volumes:
      - ./packages:/opt/sendgrid/ui-components/packages
      - ./docs:/opt/sendgrid/ui-components/docs
      - ./.git:/opt/sendgrid/ui-components/.git
      # - ~/.ssh:/root/.ssh
      - /var/lib/buildkite-agent/.ssh:/var/lib/buildkite-agent/.ssh
  develop:
    image: docker.sendgrid.net/sendgrid/ui-components:latest
    build:
      context: .
    volumes:
    - /opt/sendgrid/ui-components/node_modules
    - .:/opt/sendgrid/ui-components
    ports:
    - "6006:6006"
