
# Welcome to your pipeline.yml file. This file is what controls what is ran during your
# build. This is a direct port of the job you were running in jenkins. We've added
# some suggestions (commented out), but we have not changed any of your logic.
#
# Feel free to change it, but please remember that the more you change it, the
# less we are able to help you figure out what went wrong!
#
# For information on some of the things you can do inside of this file, please
# check out the buildkite documentation here:
# https://buildkite.com/docs/pipelines/defining-steps
steps:

  ##############################
  # Build it & Package it
  ##############################

- name: ":bash: Decide Which Pipeline To Run"
  command:
    - ./.buildkite/theDecider.sh
  # branches: "master"

# - name: ":bash: Upload Build Pipeline"
#   command:
#     - buildkite-agent pipeline upload ./buildkite/buildPipeline.yml
#   branches: "!master"
