steps:
  - block: "Request Publish"
    fields:
      - select: "Release Type"
        key: "publish_version"
        options:
          major | minor | patch | premajor | preminor | prepatch | prerelease
          - label: "major"
            value: "major"
          - label: "minor"
            value: "minor"
          - label: "patch"
            value: "patch"
          - label: "premajor"
            value: "premajor"
          - label: "preminor"
            value: "preminor"
          - label: "prepatch"
            value: "prepatch"
          - label: "prerelease"
            value: "prerelease"
  - name: "stuff"
    command: echo ${BUILDKITE_AGENT_META_DATA_PUBLISH_VERSION}
  # - name: ":yarn: :docker: Build UI-component base image"
  #   plugins:
  #     docker-compose#v2.2.1:
  #       build: app
  #       image-repository: docker.sendgrid.net/sendgrid
  #       cache-from: app:docker.sendgrid.net/sendgrid/ui-components:latest
