steps:
  - name: ":docker: Build Container"
    plugins:
      docker-compose#v2.2.1:
        build: app
        image-repository: docker.sendgrid.net/sendgrid
        cache-from: app:docker.sendgrid.net/sendgrid/ui-components:latest
  - block: ":exploding_death_star: Request Publish :exploding_death_star:"
    fields:
      - select: "Release Type"
        key: "publish-version"
        options:
          - label: "patch"
            value: "patch"
          - label: "minor"
            value: "minor"
          - label: "major"
            value: "major"
          # - label: "premajor"
          #   value: "premajor"
          # - label: "preminor"
          #   value: "preminor"
          # - label: "prepatch"
          #   value: "prepatch"
          # - label: "prerelease"
          #   value: "prerelease"

  - name: ":dragon: Lerna Publish"
    command: 
      - git fetch 
      - git checkout ${BUILDKITE_BRANCH} 
      - git pull 
      - docker-compose run app bash -c "/usr/local/bin/npx lerna publish --skip-git --skip-npm --yes --cd-version ${PUBLISH-VERSION}"
      - git status
      
      # - tar --exclude='./node_modules' --exclude='./.git' -zcvf ./buildartifact.tgz ./**/{package.json,lerna.json}
    # plugins:
      # docker-compose#v2.2.1:
      #   run: app
      #   image-repository: docker.sendgrid.net/sendgrid
      #   cache-from: app:docker.sendgrid.net/sendgrid/ui-components:latest
        

# git fetch && git checkout ${BUILDKITE_BRANCH} && git pull && /usr/local/bin/npx lerna publish --skip-git --skip-npm --yes --cd-version ${version}
  # - name: ":yarn: :docker: Build UI-component base image"
        

