steps:
  - block: "Request Publish"
    fields:
      - select: "Release Type"
        key: "publish-version"
        options:
          - label: "major"
            value: "major"
          - label: "minor"
            value: "minor"
          - label: "patch"
            value: "patch"
          - label: "premajor"
            value: "premajor"
          - label: "preminor"
            value: "preminor"
          - label: "prepatch"
            value: "prepatch"
          - label: "prerelease"
            value: "prerelease"
  - name: "stuff"
    command: npx lerna publish --skip-git --skip-npm --yes --cd-version ${buildkite-agent meta-data get "release-version"}
  - name: "stuff"
    command: npx lerna publish --skip-git --skip-npm --yes --cd-version ${buildkite-agent meta-data get "release-version"}
    plugins:
      docker-compose#v2.2.1:
        run: app
        image-repository: docker.sendgrid.net/sendgrid
        cache-from: app:docker.sendgrid.net/sendgrid/ui-components:latest

  # - name: ":yarn: :docker: Build UI-component base image"
        
