steps:
  - block: "Request Publish"
    fields:
      - select: "Release Type"
        key: "publish-version"
        options:
          - label: "patch"
            value: "patch"
          - label: "minor"
            value: "minor"
          - label: "major"
            value: "major"
          # - label: "premajor"
          #   value: "premajor"
          # - label: "preminor"
          #   value: "preminor"
          # - label: "prepatch"
          #   value: "prepatch"
          # - label: "prerelease"
          #   value: "prerelease"
  # - name: "stuff" 
  #   command: JUSTSOMESTUFF=$(buildkite-agent meta-data get "publish-version")
  - name: ":exploding_death_star: Lerna :exploding_death_star: Publish :exploding_death_star:"
    command: 
      - npx lerna publish --skip-npm --yes --cd-version $(buildkite-agent meta-data get "publish-version")
    plugins:
      docker-compose#v2.2.1:
        run: app
        image-repository: docker.sendgrid.net/sendgrid
        cache-from: app:docker.sendgrid.net/sendgrid/ui-components:latest
        # mounts:
        #   - ./.git:/opt/sendgrid/ui-components/.git

  # - name: ":yarn: :docker: Build UI-component base image"
        

